### ISSUE TITLE
No time stamps in the final file

### ISSUE THREAD

**Issue by Suleman-Elahi** [hufan-akari/lrc-maker#1]
After synchronizing the lyrics, the time stamps do not appear in the finally exported LRC file.

**Comment by hufan-akari** [comment]
Is there any errors in the browser console?

**Comment by Suleman-Elahi** [comment]
YEah... !

![image](https://user-images.githubusercontent.com/24384996/36363623-8687b2b8-1564-11e8-9967-45b715e51e38.png)

**Comment by hufan-akari** [comment]
Follow these the steps and tell me which steps don't  behave as expected.

1. paste the plain lyric text in the edit page and drag audio into page.
  *expected behavior: the audio metadata loaded, its time length will show in the page footer.*
2. select the "synchronize" button in the page header. 
  *expected behavior: your lyric text will be parsed, split by line, transformed to a list. There will be an anchor on the selected line which show the current time stamp.*
![screen shot 2018-02-19 at 3 16 30 pm](https://user-images.githubusercontent.com/7829098/36366178-e8a45d34-1587-11e8-96b3-5e8d272b2688.png)
3. play the audio (ctrl/command+return,or click the play button in the page footer), use space key to synchronize the lyric.
  *expected behavior: the timestamp will insert into selected line, and the anchor will go next line.*
![screen shot 2018-02-19 at 3 21 16 pm](https://user-images.githubusercontent.com/7829098/36366332-927edff0-1588-11e8-80ad-0da7a0128a94.png)
4. click download button will download the exported LRC file. Or navigate to the edit page, the text box content changed. It is as same as the download file's content.
---
It seems like another irrelevant problem in your screenshot. (try to read cache which does not exist.) I will fix it.

**Comment by hufan-akari** [comment]
I cannot reproduce it.
Please reopen this issue if you have more information.
